"""Mantra API endpoints — daily mantras, chalisas, aartis, and categories."""

import random
from datetime import date
from fastapi import APIRouter, HTTPException, Query

router = APIRouter(prefix="/api/v1/mantra", tags=["mantra"])


def _members(kind: str, category_id: str) -> list[str]:
    """Ids of the mantras that actually belong to a category.

    `MANTRA_CATEGORIES` carried hand-written `mantra_count` and
    `related_mantras` values, and they had drifted from `DAILY_MANTRAS`: the
    career category claimed a mantra that declares `purpose: "success"` while
    no mantra declares `purpose: "career"` at all, and peace, sun, jupiter and
    ketu were each off by one. Counting the real list means a category can
    never advertise a mantra it does not hold.
    """
    members = []
    for mantra in DAILY_MANTRAS:
        if kind == "purpose":
            match = mantra.get("purpose") == category_id
        elif kind == "planet":
            match = (mantra.get("planet") or "").lower() == category_id
        else:
            # Deity is free text ("Lord Shiva", "Savitr (Sun God)"), so the
            # category id is matched as a substring of it.
            match = category_id.lower() in (mantra.get("deity") or "").lower()
        if match:
            members.append(mantra["id"])
    return members


def _categories() -> dict:
    """Categories with their counts and members taken from the mantras."""
    return {
        kind: [
            {
                "id": entry["id"],
                "name": entry["name"],
                "description": entry["description"],
                "mantra_count": len(members),
                "related_mantras": members,
            }
            for entry in entries
            for members in [_members(kind, entry["id"])]
        ]
        for kind, entries in MANTRA_CATEGORIES.items()
    }


# ---------------------------------------------------------------------------
# Vedic Mantras — Daily mantras with meaning, benefits, and deity
# ---------------------------------------------------------------------------

DAILY_MANTRAS = [
    {
        "id": "gayatri_mantra",
        "deity": "Savitr (Sun God)",
        "mantra_hindi": "ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्",
        "transliteration": "Om Bhur Bhuvaḥ Svaḥ Tat Savitur Vareṇyaṃ Bhargo Devasya Dhīmahi Dhiyo Yo Naḥ Prachodayāt",
        "meaning": "We meditate upon the glorious splendour of the divine light of Savitur (the Sun God). May he illuminate our intellect and guide us toward the right path.",
        "benefits": "Enhances intelligence, wisdom, and clarity of thought. Protects from negative energies and promotes spiritual awakening.",
        "best_time": "Brahma Muhurta (4:00 AM - 5:30 AM)",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "wisdom",
        "planet": "Sun"
    },
    {
        "id": "mahamrityunjaya_mantra",
        "deity": "Lord Shiva",
        "mantra_hindi": "ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम् उर्वारुकमिव बन्धनान् मृत्योर्मुक्षीय मामृतात्",
        "transliteration": "Om Tryambakam Yajāmahe Sugandhiṃ Puṣṭivardhanam Urvarukamiva Bandhanān Mṛtyormukṣīya Māmṛtāt",
        "meaning": "We worship the three-eyed Lord Shiva who nourishes all beings. As the cucumber is freed from its bondage to the vine, may we be liberated from death and led to immortality.",
        "benefits": "Overcomes fear of death, promotes longevity, cures chronic diseases, removes negative karma, and brings inner peace.",
        "best_time": "Early morning or during Sandhya times",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "health",
        "planet": "Saturn"
    },
    {
        "id": "ganesh_mantra",
        "deity": "Lord Ganesha",
        "mantra_hindi": "ॐ गं गणपतये नमः",
        "transliteration": "Om Gaṃ Gaṇapataye Namaḥ",
        "meaning": "Salutations to Lord Ganesha, the remover of obstacles and the lord of beginnings.",
        "benefits": "Removes obstacles, brings success in new ventures, grants wisdom and prosperity. Ideal before starting any important work.",
        "best_time": "Early morning or before any new beginning",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "success",
        "planet": "Ketu"
    },
    {
        "id": "lakshmi_mantra",
        "deity": "Goddess Lakshmi",
        "mantra_hindi": "ॐ श्रीं महालक्ष्म्यै नमः",
        "transliteration": "Om Śrīṃ Mahālakṣmyai Namaḥ",
        "meaning": "Salutations to the great Goddess Lakshmi, the divine mother of wealth, fortune, and prosperity.",
        "benefits": "Attracts wealth, abundance, and material prosperity. Removes financial difficulties and brings stability.",
        "best_time": "Friday evenings during dusk",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "wealth",
        "planet": "Venus"
    },
    {
        "id": "saraswati_mantra",
        "deity": "Goddess Saraswati",
        "mantra_hindi": "ॐ ऐं सरस्वत्यै नमः",
        "transliteration": "Om Aim Sarasvatyai Namaḥ",
        "meaning": "Salutations to Goddess Saraswati, the divine mother of knowledge, music, arts, and wisdom.",
        "benefits": "Enhances knowledge, academic success, creativity, and mastery over arts and sciences. Removes ignorance.",
        "best_time": "Early morning during Brahma Muhurta",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "wisdom",
        "planet": "Jupiter"
    },
    {
        "id": "durga_mantra",
        "deity": "Goddess Durga",
        "mantra_hindi": "ॐ दुं दुर्गायै नमः",
        "transliteration": "Om Duṃ Durgāyai Namaḥ",
        "meaning": "Salutations to Goddess Durga, the invincible protector who destroys all evil and grants strength.",
        "benefits": "Provides protection from enemies, removes fears, grants courage and strength. Overcomes difficult situations.",
        "best_time": "Tuesday or Saturday evenings",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "protection",
        "planet": "Mars"
    },
    {
        "id": "hanuman_mantra",
        "deity": "Lord Hanuman",
        "mantra_hindi": "ॐ हं हनुमते नमः",
        "transliteration": "Om Haṃ Hanumate Namaḥ",
        "meaning": "Salutations to Lord Hanuman, the monkey god of courage, devotion, and selfless service.",
        "benefits": "Grants courage, strength, and protection from evil spirits. Removes obstacles and fears. Bestows devotion.",
        "best_time": "Tuesday or Saturday mornings",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "protection",
        "planet": "Saturn"
    },
    {
        "id": "vishnu_mantra",
        "deity": "Lord Vishnu",
        "mantra_hindi": "ॐ नमो भगवते वासुदेवाय",
        "transliteration": "Om Namo Bhagavate Vāsudevāya",
        "meaning": "Salutations to the Supreme Lord Vishnu, the preserver and sustainer of the universe.",
        "benefits": "Brings peace, harmony, and divine protection. Removes negativity and grants liberation from worldly sufferings.",
        "best_time": "Thursday mornings",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "peace",
        "planet": "Jupiter"
    },
    {
        "id": "shiva_mantra",
        "deity": "Lord Shiva",
        "mantra_hindi": "ॐ नमः शिवाय",
        "transliteration": "Om Namaḥ Śivāya",
        "meaning": "Salutations to Lord Shiva, the auspicious one, the destroyer of evil and transformer of the universe.",
        "benefits": "Brings inner peace, destroys negative karma, promotes spiritual growth, and grants liberation.",
        "best_time": "Monday mornings or during Pradosh",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "peace",
        "planet": "Saturn"
    },
    {
        "id": "raam_mantra",
        "deity": "Lord Rama",
        "mantra_hindi": "ॐ श्री रामाय नमः",
        "transliteration": "Om Śrī Rāmāya Namaḥ",
        "meaning": "Salutations to Lord Rama, the ideal man, the seventh avatar of Vishnu, and the embodiment of dharma.",
        "benefits": "Purifies the mind, grants moral strength, removes bad karma, and promotes righteous living.",
        "best_time": "Tuesday or Saturday mornings",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "peace",
        "planet": "Sun"
    },
    {
        "id": "krishna_mantra",
        "deity": "Lord Krishna",
        "mantra_hindi": "ॐ कृष्णाय वासुदेवाय हरये परमात्मने प्रणतः क्लेशनाशाय गोविन्दाय नमो नमः",
        "transliteration": "Om Kṛṣṇāya Vāsudevāya Haraye Paramātmane Praṇataḥ Kleśanāśāya Govindāya Namo Namaḥ",
        "meaning": "Salutations again and again to Lord Krishna, the son of Vasudeva, the supreme soul, who destroys all sufferings.",
        "benefits": "Brings divine love, removes ego, grants spiritual liberation, and fills the heart with devotion and joy.",
        "best_time": "Wednesday evenings or Janmashtami",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "love",
        "planet": "Jupiter"
    },
    {
        "id": "surya_mantra",
        "deity": "Sun God (Surya)",
        "mantra_hindi": "ॐ सूर्याय नमः",
        "transliteration": "Om Sūryāya Namaḥ",
        "meaning": "Salutations to the Sun God, the source of all life, energy, and vitality in the universe.",
        "benefits": "Promotes health, vitality, and confidence. Cures diseases, especially eye ailments. Brings leadership qualities.",
        "best_time": "Sunrise, facing the sun",
        "repetitions": 7,
        "category": "vedic",
        "purpose": "health",
        "planet": "Sun"
    },
    {
        "id": "chandra_mantra",
        "deity": "Moon God (Chandra)",
        "mantra_hindi": "ॐ चन्द्राय नमः",
        "transliteration": "Om Chandrāya Namaḥ",
        "meaning": "Salutations to the Moon God, the lord of mind, emotions, and feminine energy.",
        "benefits": "Calms the mind, enhances emotional balance, improves sleep, and strengthens intuition and psychic abilities.",
        "best_time": "Monday evening during moonrise",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "peace",
        "planet": "Moon"
    },
    {
        "id": "mangal_mantra",
        "deity": "Mars God (Mangal)",
        "mantra_hindi": "ॐ अं अंगारकाय नमः",
        "transliteration": "Om Aṃ Angārakāya Namaḥ",
        "meaning": "Salutations to Mars, the divine warrior who grants courage, strength, and protection from enemies.",
        "benefits": "Removes Manglik Dosha, grants courage, strengthens willpower, and protects from accidents and enemies.",
        "best_time": "Tuesday mornings",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "protection",
        "planet": "Mars"
    },
    {
        "id": "budh_mantra",
        "deity": "Mercury God (Budh)",
        "mantra_hindi": "ॐ बुं बुधाय नमः",
        "transliteration": "Om Buṃ Budhāya Namaḥ",
        "meaning": "Salutations to Mercury, the planet of intelligence, communication, and commerce.",
        "benefits": "Enhances communication skills, intelligence, and business acumen. Removes speech defects and skin diseases.",
        "best_time": "Wednesday mornings",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "wisdom",
        "planet": "Mercury"
    },
    {
        "id": "guru_mantra",
        "deity": "Jupiter God (Brihaspati/Guru)",
        "mantra_hindi": "ॐ ग्रां गुरवे नमः",
        "transliteration": "Om Grāṃ Gurave Namaḥ",
        "meaning": "Salutations to Jupiter, the guru of the gods, the bestower of wisdom, fortune, and spiritual knowledge.",
        "benefits": "Brings wisdom, prosperity, good fortune, and spiritual growth. Removes poverty and grants children.",
        "best_time": "Thursday mornings",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "wealth",
        "planet": "Jupiter"
    },
    {
        "id": "shukra_mantra",
        "deity": "Venus God (Shukra)",
        "mantra_hindi": "ॐ शुं शुक्राय नमः",
        "transliteration": "Om Śuṃ Śukrāya Namaḥ",
        "meaning": "Salutations to Venus, the planet of love, beauty, luxury, and artistic expression.",
        "benefits": "Attracts love, beauty, luxury, and artistic talent. Improves relationships and brings marital harmony.",
        "best_time": "Friday evenings",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "love",
        "planet": "Venus"
    },
    {
        "id": "shani_mantra",
        "deity": "Saturn God (Shani)",
        "mantra_hindi": "ॐ शं शनैश्चराय नमः",
        "transliteration": "Om Śaṃ Śanaiścarāya Namaḥ",
        "meaning": "Salutations to Saturn, the lord of karma and justice, who teaches patience and discipline.",
        "benefits": "Pacifies Shani Dosha, removes karmic debts, grants patience, discipline, and long life.",
        "best_time": "Saturday evenings during sunset",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "protection",
        "planet": "Saturn"
    },
    {
        "id": "rahu_mantra",
        "deity": "Rahu (North Lunar Node)",
        "mantra_hindi": "ॐ रां राहवे नमः",
        "transliteration": "Om Rāṃ Rāhave Namaḥ",
        "meaning": "Salutations to Rahu, the shadow planet that governs illusions, desires, and karmic lessons.",
        "benefits": "Pacifies Rahu Dosha, removes confusion, protects from black magic and negative influences.",
        "best_time": "Saturday or Wednesday evenings",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "protection",
        "planet": "Rahu"
    },
    {
        "id": "ketu_mantra",
        "deity": "Ketu (South Lunar Node)",
        "mantra_hindi": "ॐ कें केतवे नमः",
        "transliteration": "Om Keṃ Ketave Namaḥ",
        "meaning": "Salutations to Ketu, the shadow planet of spirituality, liberation, and past-life karma.",
        "benefits": "Pacifies Ketu Dosha, enhances spiritual growth, grants moksha (liberation), and removes past-life karmic debts.",
        "best_time": "Saturday or Tuesday evenings",
        "repetitions": 108,
        "category": "vedic",
        "purpose": "peace",
        "planet": "Ketu"
    },
]


# ---------------------------------------------------------------------------
# Chalisas — Full text of popular Hindu chalisas
# ---------------------------------------------------------------------------

CHALISAS = [
    {
        "id": "hanuman_chalisa",
        "deity": "Lord Hanuman",
        "author": "Tulsidas",
        "language": "Hindi/Awadhi",
        "description": "A 40-verse hymn dedicated to Lord Hanuman, composed by Goswami Tulsidas. It extols the virtues, exploits, and devotion of Hanuman.",
        "verses_hindi": [
            "श्रीगुरु चरन सरोज रज, निज मनु मुकुरु सुधारि।",
            "बरनउँ रघुबर बिमल जसु, जो दायकु फल चारि॥",
            "बुद्धिर्बल यशो धैर्य, निर्भयता अमित विक्रम।",
            "जाप्य पवित्र चंचल कपि, जो सुनके कुसल विक्रम॥",
            "जय हनुमान ज्ञान गुन सागर।",
            "जय कपीस तिहुँ लोक उजागर॥",
            "रामदूत अतुलित बल धामा।",
            "अंजनि-पुत्र पवनसुत नामा॥",
            "महाबीर बिक्रम बजरंगी।",
            "कुमति निवार सुमति के संगी॥",
            "कञ्चन बरन बिराज सुबेसा।",
            "कानन कुण्डल कुँचित केसा॥",
            "हाथ बज्र औ ध्वजा बिराजै।",
            "काँधे मूँज जनेऊ साजै॥",
            "शंकर सुवन केसरीनंदन।",
            "तेज प्रताप महा जग वंदन॥",
            "विद्यावान गुनी अति चातुर।",
            "राम काज कीन्हें को आतुर॥",
            "प्रभु चरित्र सुनिबे को रसिया।",
            "रामलखन सीता मन बसिया॥",
            "सूक्ष्म रूप धरि सियहिं दिखावा।",
            "विकट रूप धरि लंक जरावा॥",
            "भीम रूप धरि असुर सँघारे।",
            "रामचन्द्र के काज सँवारे॥",
            "लाय संजीवन लखन जियाये।",
            "श्रीरघुबीर हरषि उर लाये॥",
            "रघुपति कीन्ही बहु बड़ाई।",
            "तुम मम प्रिय भरतहि सम भाई॥",
            "सहस बदन तुम्हरो जस गावैं।",
            "अस कहि श्रीपति कंठ लगावैं॥",
            "नम मनोरथ लाखन जगत उजियारे।",
            "तुम्हरे भजन राम पर भरते॥",
            "अन्य देवता चित्त न धरई।",
            "हनुमत सेई सर्ब सुख करई॥",
            "सँकट मोचन हनुमत विख्यात।",
            "जग निवास अतुलित बल जाता॥",
            "बुद्धिर्बल यशो धैर्य, निर्भयता अमित विक्रम।",
            "जाप्य पवित्र चंचल कपि, जो सुनके कुसल विक्रम॥",
            "जो सत बार पाठ कर कोई।",
            "छूटहि बंदि महा सुख होई॥",
            "जो यह पढ़ै हनुमान चालीसा।",
            "हय सिद्दि साखी गौरीसा॥",
            "तुलसीदास सदा हरि चेरा।",
            "कीजै नाथ हृदय मँह डेरा॥",
            "पवनतनय संकट हरन, मंगल मूरति रूप।",
            "रामलखन सीता सहित, हृदय बसहु सुर भूप॥",
        ],
        "verses_transliteration": [
            "Śrīguru charana saroja raja, nija mana mukuru sudhāri.",
            "Baranau Raghubara bimala jasu, jo dāyaku phala chāri.",
            "Buddhirbala yasho dhairya, nirbhayatā amita vikrama.",
            "Jāpya pavitra chanchala kapi, jo sunake kusala vikrama.",
            "Jaya Hanumāna jñāna.guna sāgara.",
            "Jaya Kapīsa tihu loka ujāgara.",
            "Rāmadūta atulita bala dhāmā.",
            "Añjani-putra Pavanasuta nāmā.",
            "Mahābīra bikrama Bajrangī.",
            "Kumati nivāra sumati ke saṅgī.",
            "Kañchana barana birāja subesā.",
            "Kānana kuṇḍala kuñchita kesā.",
            "Hātha bajra au dhwajā birājai.",
            "Kāndhe mūnja janeū sājai.",
            "Shaṅkara suvana Kesarīnandana.",
            "Teja prataapa mahā jaga vandana.",
            "Vidyāvāna gunī ati chātura.",
            "Rāma kāja kīne ko ātura.",
            "Prabhu charitra sunibe ko rasiyā.",
            "Rāmalakhana Sītā mana basiyā.",
            "Sūkṣhma rūpa dhari Sīyahim dikhāvā.",
            "Vikaṭa rūpa dhari Laṅkā jarāvā.",
            "Bhīma rūpa dhari asura saṅghāre.",
            "Rāmachandra ke kāja saṅvāre.",
            "Lāya sañjīvana Lakhana jiyāye.",
            "ŚrīRaghuvīra haraṣhi ure lāye.",
            "Raghupati kīnhī bahut baḍāī.",
            "Tuma mama priya Bharatahi sam bhāī.",
            "Sahasra badana tumharo jasa gāvai.",
            "Asa kahi Śrīpati kaṇṭha lagāvai.",
            "Nama manoratha Lākhana jagata ujiyāre.",
            "Tumharo bhajana Rāma para bharate.",
            "Anyadevata citta na dharai.",
            "Hanumata seī sarba sukha karai.",
            "Saṅkata mochana Hanumata vikhyāta.",
            "Jaga nivāsa atulita bala jātā.",
            "Buddhirbala yasho dhairya, nirbhayatā amita vikrama.",
            "Jāpya pavitra chanchala kapi, jo sunake kusala vikrama.",
            "Jo sata bāra pāṭha kara koī.",
            "Chhuṭahi bandi mahā sukh hoī.",
            "Jo yaha paṛhai Hanumāna chālīsā.",
            "Haya siddhi sākhī Gaurīsā.",
            "Tulasīdāsa sadā Harī cherā.",
            "Kījai nātha hṛdaya mah̐ ḍerā.",
            "Pavanatanaya saṅkata harana, mangala mūrati rūpa.",
            "Rāmalakhana Sītā sahita, hṛdaya basahu sura bhūpa.",
        ],
    },
    {
        "id": "durga_chalisa",
        "deity": "Goddess Durga",
        "author": "Traditional",
        "language": "Hindi",
        "description": "A 40-verse hymn dedicated to Goddess Durga, the divine mother who destroys evil and protects her devotees.",
        "verses_hindi": [
            "नमो नमो दुर्गति नाशिनी, नमो नमो अम्बे।",
            "पूर्ण करो सब अभिलाष, हे सुर वर अम्बे॥",
            "नमो नमो दुर्गति नाशिनी, नमो नमो अम्बे।",
            "पूर्ण करो सब अभिलाष, हे सुर वर अम्बे॥",
            "तुमको दश प्रकार पूजा, श्रद्धा भक्ति में।",
            "देवी प्रकट तुम रहता, हर युग में तुम अम्बे॥",
            "विश्व विनय जग वंदना, स्तुती विप्रन की।",
            "जो भी जन कष्ट मिटाये, मुक्ती करे वो नारी की॥",
            "जैसे सूर्य किरण से अँधेरा छंज जाए।",
            "वैसे ही माँ तेरी कृपा से सब दूर हो जाए॥",
            "नमो नमो दुर्गति नाशिनी, नमो नमो अम्बे।",
            "पूर्ण करो सब अभिलाष, हे सुर वर अम्बे॥",
            "शंकर जी शैल पर जाके, गौरी माँ को ले आए।",
            "गणेश, कार्तिक देव विख्यात, शेर पर सवार माँ जाए॥",
            "विंध्य हिमालय पर विराजे, नैना में नील रंग।",
            "जो भी कोई माँ को देखे, तो मन रहे उत्संग॥",
            "नमो नमो दुर्गति नाशिनी, नमो नमो अम्बे।",
            "पूर्ण करो सब अभिलाष, हे सुर वर अम्बे॥",
            "तुम वैसे शेर पर सवार, अनहद नाद से भैया।",
            "सिंह को देख करके दानव, भाग जाते हैं छैया॥",
            "माँ तुम्हारे ही कर कमल, से वार तलवार है।",
            "शत्रु सब का नाश करतीं, यही तेरा ध्यान है॥",
            "नमो नमो दुर्गति नाशिनी, नमो नमो अम्बे।",
            "पूर्ण करो सब अभिलाष, हे सुर वर अम्बे॥",
            "सारे संसार में तुम्हीं, कल्याण रूप हो।",
            "तुम ही माँ तुम ही हो, हर संकट का नाश तुम्हीं करती हो॥",
            "नवरात्र में भक्त जन, करते तुमको पूजा।",
            "तुम बिना अन्न और धन का, ना हो सके उपजा॥",
            "नमो नमो दुर्गति नाशिनी, नमो नमो अम्बे।",
            "पूर्ण करो सब अभिलाष, हे सुर वर अम्बे॥",
            "कोई भी जन जो दुर्गा माँ को ध्याये।",
            "गर्भ संकट और शत्रु का नाश उसका हो जाये॥",
            "दुर्गा चालीसा जो जन गावे।",
            "सब सुख समृद्धि उसके घर आवे॥",
            "नमो नमो दुर्गति नाशिनी, नमो नमो अम्बे।",
            "पूर्ण करो सब अभिलाष, हे सुर वर अम्बे॥",
            "जो पढ़े दुर्गा चालीसा का पाठ।",
            "उसकी बुरी किस्मत का हो जाता है नाश॥",
            "अंत में जो दुर्गा माँ का गुन गाये।",
            "उसके कष्ट मिट जाएँ, सुख संपत्ति आये॥",
            "नमो नमो दुर्गति नाशिनी, नमो नमो अम्बे।",
            "पूर्ण करो सब अभिलाष, हे सुर वर अम्बे॥",
            "बोलो माँ दुर्गति नाशिनी की जय।",
            "नमो नमो अम्बे, पूर्ण करो सब अभिलाष।",
        ],
    },
    {
        "id": "ganesh_chalisa",
        "deity": "Lord Ganesha",
        "author": "Traditional",
        "language": "Hindi",
        "description": "A 40-verse hymn dedicated to Lord Ganesha, the remover of obstacles and the lord of beginnings.",
        "verses_hindi": [
            "जय गणपति सर्व विघ्न को नाशिनी।",
            "बुद्धि विवेक शक्ति के दाता, सब विपद को हरिनी॥",
            "बुद्धिर्बल यशो धैर्य, निर्भयता अमित विक्रम।",
            "जाप्य पवित्र चंचल कपि, जो सुनके कुसल विक्रम॥",
            "जय गणेश गजानन, सिद्धि विनायक।",
            "वक्रतुंड महाकाय, सूर्य कोटि समप्रभा॥",
            "निर्विघ्न करो सब काज, हे विघ्न विनाशिनी।",
            "मोदक प्रिय गुड़ भोग, नित चढ़ावत जननी॥",
            "चंद्र वर्ण अति शोभा, मुषक वाहन सज्जित।",
            "एक दंत शूर वीर, चार भुजा अति सुशोभित॥",
            "पर्वत पर जो विराजे, देवता दल निवासी।",
            "सिद्धि-बुद्धि सदा वर्द्धी, बुद्धि विवेक विकासी॥",
            "गणपति से जो नर पूजे, सब काज में सफल होए।",
            "शुभ गुण सब उसमें आए, नाम सुनते ही कलेजा ठंडा होए॥",
            "नमो नमो गणपति देव, श्री गुरु कृपा कीनी।",
            "बोलो माँ की जय गणेश, सुख समृद्धि दीनी॥",
            "दीनदयाल बुद्धि के दाता, बुद्धि विवेक शक्ति।",
            "वक्रतुंड गजानन, सुख-समृद्धि मुक्ति॥",
            "जो कोई यह चालीसा पढ़े, सब सुख लाभ होए।",
            "गणपति उनके सब दुख हरें, सौभाग्य बढ़ जाए॥",
            "नमो नमो गणपति देव, श्री गुरु कृपा कीनी।",
            "बोलो माँ की जय गणेश, सुख समृद्धि दीनी॥",
            "मनोकामना जो मांगे, सब पूर्ण हो जाए।",
            "गणेश कृपा जिस पर बरसे, उसके सब कष्ट मिट जाए॥",
            "देवता सुर नर मुनि सुमिरे, यश पाए।",
            "गणेश चालीसा जो गावे, सब सिद्धि पाए॥",
            "नमो नमो गणपति देव, श्री गुरु कृपा कीनी।",
            "बोलो माँ की जय गणेश, सुख समृद्धि दीनी॥",
            "बोलो जय गणेश देवा, वक्रतुंड महाराज।",
            "जन के कष्ट हरता है, देता सबको सुख साज॥",
            "गणपति बप्पा मोरया, मंगल मूर्ति रूप।",
            "रिद्धि-सिद्धि दे तुम मोरे, करें सदा सत्य स्वरूप॥",
            "जो गणेश की चालीसा पढ़े, नित प्रातः श्रद्धा से।",
            "उसके सब कष्ट मिट जाएँ, पूर्ण हो उसकी हर इच्छा॥",
            "नमो नमो गणपति देव, श्री गुरु कृपा कीनी।",
            "बोलो माँ की जय गणेश, सुख समृद्धि दीनी॥",
            "जय जय जय गणपति देवा, सिद्धि विनायक।",
            "शत्रु विनाश और सुख-शांति, सदा तुम्हीं से पाकर जाए भक्त जनाक॥",
        ],
    },
    {
        "id": "shiv_chalisa",
        "deity": "Lord Shiva",
        "author": "Traditional",
        "language": "Hindi",
        "description": "A 40-verse hymn dedicated to Lord Shiva, the destroyer of evil and the lord of meditation and yoga.",
        "verses_hindi": [
            "जय शिव ओंकार, बम भोलेनाथ।",
            "त्रिशूल धारी, महेश्वर विभु॥",
            "प्रथम ब्रह्मा, दूसरे विष्णु, तीसरे महेश्वर।",
            "प्रकृति से सब उत्पन्न, प्रकृति ही सब शश्वर॥",
            "जय शिव ओंकार, बम भोलेनाथ।",
            "त्रिशूल धारी, महेश्वर विभु॥",
            "हरिहर विश्व विख्यात, रुद्र स्वरूप धारी।",
            "रंग भूतनाथ प्रकट, सदा शान्ति कर्ता॥",
            "नीलकंठ प्रभु शंभू, प्रणवाक्षर में राजे।",
            "तीनों लोक में बाजे, नाद भूत विश्व विख्यात॥",
            "शिव समर्थ शिव शक्ति, भक्तों के कल्याण।",
            "शत्रुनाशक मंगलकर्ता, परम प्रभु भगवान॥",
            "चन्द्रमौलि सदा शोभा, नील वस्त्र धारी।",
            "मकर कुंडल शोभित, मुनिजन मन हारी॥",
            "गंगा बहे जटा में, गण बैठे उपर सार।",
            "बाघम्बर तन धारी, भूत प्रेत निकर निवासी॥",
            "जय शिव ओंकार, बम भोलेनाथ।",
            "त्रिशूल धारी, महेश्वर विभु॥",
            "गण नाथ नंदी बैशाख, ब्रह्मा विष्णु समान।",
            "शेषनाग मणिशेखर, सुर नर मुनिजन गुणगान॥",
            "कैलाश मानसरोवर, मध्य वास अर्धांगी।",
            "योगी यत सुमिरत, शिव हैं सुखदाई॥",
            "काशी में विराजे, विश्वनाथ शिव गिरीश।",
            "तीर वाराणसी में, मुक्ति का द्वार है शिव की कृपा से॥",
            "शिव की रचना देवता, मानव और पशु पक्षी।",
            "निर्माण करते शिव अपने, कर देते सब का कल्याण॥",
            "शिव को सब गुण विद्यमान, दोष मुक्त हैं शिव शंकर।",
            "सब के प्राण प्यारे, शिव हैं सुख कर्ता॥",
            "जय शिव ओंकार, बम भोलेनाथ।",
            "त्रिशूल धारी, महेश्वर विभु॥",
            "शिव की शरण में जो आये, सुख समृद्धि पाए।",
            "शिव भक्ति जिसके हृदय में, मोक्ष का मार्ग पाए॥",
            "नित प्रातः शिव का नाम, जपे जो मन लगाकर।",
            "शिव कृपा उस पर बरसे, कष्ट मिटे सारे अंतर्गत विकार॥",
            "शिव की चालीसा जो पढ़े, श्रद्धा भक्ति से।",
            "शिव उसके सब संकट हरें, दें सुख-शांति निर्वेश से॥",
            "जय शिव ओंकार, बम भोलेनाथ।",
            "त्रिशूल धारी, महेश्वर विभु॥",
            "ओं नमः शिवाय, जपो शिव नाम।",
            "शिव से बड़ा न कोई, शिव हैं परम कल्याण काम॥",
            "बोलो जय महेश्वर, बम भोलेनाथ।",
            "शिव सदा सहायक हैं, भक्तों का सुख विविध विभु॥",
        ],
    },
    {
        "id": "vishnu_chalisa",
        "deity": "Lord Vishnu",
        "author": "Traditional",
        "language": "Hindi",
        "description": "A 40-verse hymn dedicated to Lord Vishnu, the preserver and sustainer of the universe.",
        "verses_hindi": [
            "जय विष्णु भगवान वासुदेव।",
            "श्रीमन्नारायण विठ्ठल स्वामी॥",
            "जय विष्णु हरि वासुदेव, नित श्रद्धा से जो जपे।",
            "सब सुख लाभ हो जाए, कष्ट मिट जाएँ सारे॥",
            "चार भुजा कोटि सूर्य सम, शंख चक्र गदा धारी।",
            "गिरिजा शंकर विश्वरूप, त्रिलोक विख्यात नाम तुम्हारा॥",
            "विश्वभरण पोषण कर्ता, सुर सुरित नर ऋषि भक्त सेवित।",
            "विश्व विधायक जगत पालक, सब के प्रभु निरंतर स्वामी॥",
            "जय विष्णु हरि वासुदेव, नित श्रद्धा से जो जपे।",
            "सब सुख लाभ हो जाए, कष्ट मिट जाएँ सारे॥",
            "क्षीरसागर में विराजे, लक्ष्मी जी संग विभु।",
            "शेष शैया पर लेटे, चारों भुजा विस्तृत हैं॥",
            "वराह रूप में प्रकटे, भूमि को उठाया।",
            "नरसिंह रूप में आके, हिरण्याक्ष का नाश किया॥",
            "वामन रूप में आकर, तीन पग में नापा।",
            "बलि राजा को वचन दिया, पाताल लोक तक छापा॥",
            "जय विष्णु हरि वासुदेव, नित श्रद्धा से जो जपे।",
            "सब सुख लाभ हो जाए, कष्ट मिट जाएँ सारे॥",
            "राम अवतार में आकर, लंका को जीता।",
            "रावण का वध किया, धर्म की ज्योति जलाया॥",
            "कृष्ण रूप में प्रकटे, गोवर्धन उठाया।",
            "कंस का वध किया, द्वारका में राज किया॥",
            "बुद्ध रूप में आकर, अहिंसा का संदेश दिया।",
            "जग को ज्ञान का मार्ग दिखाया, मोह-माया से मुक्त किया॥",
            "जय विष्णु हरि वासुदेव, नित श्रद्धा से जो जपे।",
            "सब सुख लाभ हो जाए, कष्ट मिट जाएँ सारे॥",
            "कल्कि अवतार आएगा, अंत समय में।",
            "पापियों का नाश करेगा, सत्य युग का आरंभ करेगा॥",
            "विष्णु चालीसा जो पढ़े, श्रद्धा भक्ति से।",
            "विष्णु कृपा उस पर बरसे, सुख-समृद्धि निश्चित है।।",
            "जय विष्णु हरि वासुदेव, नित श्रद्धा से जो जपे।",
            "सब सुख लाभ हो जाए, कष्ट मिट जाएँ सारे॥",
            "नित विष्णु का नाम जपे, सब सुख पाए।",
            "विष्णु कृपा बिना, कोई भी मुक्त ना हो पाए॥",
            "बोलो जय विष्णु भगवान, वासुदेव।",
            "श्रीमन्नारायण विठ्ठल स्वामी, सबका कल्याण करें॥",
        ],
    },
    {
        "id": "saraswati_chalisa",
        "deity": "Goddess Saraswati",
        "author": "Traditional",
        "language": "Hindi",
        "description": "A 40-verse hymn dedicated to Goddess Saraswati, the divine mother of knowledge, music, arts, and wisdom.",
        "verses_hindi": [
            "जय सरस्वती माँ, ज्ञान की देवी।",
            "बुद्धि विद्या दायिनी, श्री वीणा वादिनी॥",
            "जय सरस्वती माँ, ज्ञान की देवी।",
            "बुद्धि विद्या दायिनी, श्री वीणा वादिनी॥",
            "श्वेत वस्त्र धारिणी, वीणा कर में धारी।",
            "माँ सरस्वती सदा, करतीं कुशल उपकारी॥",
            "नील नयन शीतल, स्वर्ण सिंहासन बैठी।",
            "चंद्रमा से शीतल, कमल पर विराजित॥",
            "जय सरस्वती माँ, ज्ञान की देवी।",
            "बुद्धि विद्या दायिनी, श्री वीणा वादिनी॥",
            "गणेश के संग विराजे, विद्या का वरदान देतीं।",
            "मूर्ख को भी विद्वान बनाएं, सुख-समृद्धि देतीं॥",
            "सरस्वती की भक्ति जिसके मन में बसे।",
            "उसके जीवन में सदा, ज्ञान की ज्योति जले॥",
            "विद्यार्थी जो सेवे माँ, परीक्षा में सफल होए।",
            "संगीतकार सदा, वीणा की ध्वनि गाएं॥",
            "जय सरस्वती माँ, ज्ञान की देवी।",
            "बुद्धि विद्या दायिनी, श्री वीणा वादिनी॥",
            "माँ सरस्वती की कृपा जिस पर बरसे।",
            "उसके जीवन में सदा, सफलता के फूल खिलें॥",
            "जो माँ का स्मरण करे, नित प्रातः श्रद्धा से।",
            "उसकी बुद्धि तेज होए, ज्ञान की गंगा बहे॥",
            "सरस्वती चालीसा जो पढ़े, माँ की कृपा पाए।",
            "विद्या-बुद्धि धन दौलत, सब उसको मिल जाए॥",
            "जय सरस्वती माँ, ज्ञान की देवी।",
            "बुद्धि विद्या दायिनी, श्री वीणा वादिनी॥",
            "माँ सरस्वती की वीणा की, स्वर लहरियाँ।",
            "जीवन में सुख-शांति के, रंग भर दें सारी नियति सुहावनी हो जाए॥",
            "ज्ञान प्राप्त करने के लिए, माँ सरस्वती की पूजा करो।",
            "हर संकट मिट जाएगा, जीवन में सुख-शांति भर जाएगा॥",
            "जय सरस्वती माँ, ज्ञान की देवी।",
            "बुद्धि विद्या दायिनी, श्री वीणा वादिनी॥",
            "बोलो जय सरस्वती माँ, वीणा वादिनी।",
            "बुद्धि विद्या दायिनी, सबकी कल्याण करनी॥",
        ],
    },
    {
        "id": "lakshmi_chalisa",
        "deity": "Goddess Lakshmi",
        "author": "Traditional",
        "language": "Hindi",
        "description": "A 40-verse hymn dedicated to Goddess Lakshmi, the divine mother of wealth, fortune, and prosperity.",
        "verses_hindi": [
            "जय लक्ष्मी माँ, धन की देवी।",
            "सत्य स्वरूप जग वंदित, सब के जीवन में सुख भरी॥",
            "जय लक्ष्मी माँ, धन की देवी।",
            "सत्य स्वरूप जग वंदित, सब के जीवन में सुख भरी॥",
            "हीरे-मोती की माला, कमल पर सिंहासन बैठी।",
            "स्वर्ण कलश हाथ में, सुख-समृद्धि का वरदान देतीं॥",
            "श्वेत वस्त्र धारिणी, कमल नयन सुंदर।",
            "चंद्रमा से शीतल, जग में सबसे प्यारी माँ हैं तुम॥",
            "जय लक्ष्मी माँ, धन की देवी।",
            "सत्य स्वरूप जग वंदित, सब के जीवन में सुख भरी॥",
            "विष्णु भगवान की पत्नी, नारायणी तुम अम्बे।",
            "श्रीमन्नारायण के चरणों में, सदा निवास तुम्हारा है॥",
            "तुम्हारे दर्शन मात्र से, सब सुख प्राप्त होए।",
            "तुम्हारी कृपा दृष्टि से, सब कष्ट मिट जाएं॥",
            "धन-धान्य से भरे घर, सुख-समृद्धि बढ़े।",
            "जहाँ तुम विराजमान हो, वहाँ दरिद्रता ना रहे॥",
            "जय लक्ष्मी माँ, धन की देवी।",
            "सत्य स्वरूप जग वंदित, सब के जीवन में सुख भरी॥",
            "नित प्रातः तुम्हारा स्मरण, श्रद्धा से जो करे।",
            "उसके सब कष्ट मिट जाएँ, सुख-समृद्धि घर में भर जाए॥",
            "लक्ष्मी चालीसा जो पढ़े, माँ की कृपा पाए।",
            "धन-धान्य से भरे घर, सुख-समृद्धि सदा बढ़ाए॥",
            "जय लक्ष्मी माँ, धन की देवी।",
            "सत्य स्वरूप जग वंदित, सब के जीवन में सुख भरी॥",
            "तुम पर सेवा और भक्ति जो करें।",
            "माँ लक्ष्मी उन पर कृपा बरसाएं, सुख-समृद्धि भर जाएं॥",
            "माँ लक्ष्मी की कृपा जिस पर बरसे।",
            "उसके जीवन में सदा, सोने की बारिश होए॥",
            "जय लक्ष्मी माँ, धन की देवी।",
            "सत्य स्वरूप जग वंदित, सब के जीवन में सुख भरी॥",
            "लक्ष्मी चालीसा जो पढ़े, नित प्रातः श्रद्धा से।",
            "उसके सब कष्ट मिट जाएँ, धन-धान्य भर जाएँ सब ओर से॥",
            "बोलो जय लक्ष्मी माँ, धन की देवी।",
            "सत्य स्वरूप जग वंदित, सुख-समृद्धि भरी॥",
        ],
    },
]


# ---------------------------------------------------------------------------
# Aartis — Full text of popular Hindu aartis
# ---------------------------------------------------------------------------

AARTIS = [
    {
        "id": "ganesh_aarti",
        "deity": "Lord Ganesha",
        "aarti_name": "जय गणेश जय गणेश जय गणेश देवा",
        "language": "Hindi",
        "description": "Popular aarti for Lord Ganesha, performed at the beginning of any auspicious ceremony.",
        "aarti_hindi": [
            "जय गणेश जय गणेश जय गणेश देवा।",
            "माता जाकी पार्वती पिता महादेवा॥",
            "एक दंत दयावंत, चार भुजा धरी।",
            "माथे पर तिलक सोहे, मूसे की सवारी॥",
            "पान चढ़े फल चढ़े और चढ़े मेवा।",
            "लड्डुओं का भोग लगे, संत करें सेवा॥",
            "जय गणेश जय गणेश जय गणेश देवा।",
            "माता जाकी पार्वती पिता महादेवा॥",
            "दिन श्रद्धा की तिथि और मधुर नाम।",
            "शंकर सुमिरे संकट हरे मंगल काम॥",
            "जय गणेश जय गणेश जय गणेश देवा।",
            "माता जाकी पार्वती पिता महादेवा॥",
            "देवता यह बड़े दयाल, श्रद्धा रखो फल पाओ।",
            "मंदिर में बैठे गणपति, जन बलिहारे जाओ॥",
            "जय गणेश जय गणेश जय गणेश देवा।",
            "माता जाकी पार्वती पिता महादेवा॥",
            "गणपति बप्पा मोरया, मंगल मूर्ति रूप।",
            "श्री गणेश उद्धार करे, संकट मोचन स्वरूप॥",
            "जय गणेश जय गणेश जय गणेश देवा।",
            "माता जाकी पार्वती पिता महादेवा॥",
        ],
        "aarti_transliteration": [
            "Jaya Gaṇeśa jaya Gaṇeśa jaya Gaṇeśa devā.",
            "Mātā jākī Pārvatī pitā Mahādevā.",
            "Eka danta dayāvaṃta, chāru bhujā dharī.",
            "Māthe para tilaka sohe, mūse kī savārī.",
            "Pāna chaṛhe phala chaṛhe aura chaṛhe mevā.",
            "Laḍḍuōṅ kā bhoga lage, santa kare sevā.",
            "Jaya Gaṇeśa jaya Gaṇeśa jaya Gaṇeśa devā.",
            "Mātā jākī Pārvatī pitā Mahādevā.",
            "Dina śraddhā kī tithi aura madhura nāma.",
            "Śaṅkara sumire saṅkaṭ hare maṅgala kāma.",
            "Jaya Gaṇeśa jaya Gaṇeśa jaya Gaṇeśa devā.",
            "Mātā jākī Pārvatī pitā Mahādevā.",
            "Devatā yaha baḍe dayāla, śraddhā rakho phala pāo.",
            "Maṃdira meṃ baiṭhe Gaṇapati, jana balihāre jāo.",
            "Jaya Gaṇeśa jaya Gaṇeśa jaya Gaṇeśa devā.",
            "Mātā jākī Pārvatī pitā Mahādevā.",
            "Gaṇapati Bappā Moraya, maṅgala mūrti rūpa.",
            "Śrī Gaṇeśa uddhāra kare, saṅkaṭ mocana svārūpa.",
            "Jaya Gaṇeśa jaya Gaṇeśa jaya Gaṇeśa devā.",
            "Mātā jākī Pārvatī pitā Mahādevā.",
        ],
    },
    {
        "id": "lakshmi_aarti",
        "deity": "Goddess Lakshmi",
        "aarti_name": "जय लक्ष्मी माँ तुमको वंदना",
        "language": "Hindi",
        "description": "Popular aarti for Goddess Lakshmi, performed on Fridays and during Diwali.",
        "aarti_hindi": [
            "जय लक्ष्मी माँ तुमको वंदना।",
            "तुम पर निश्चय मेरा मन रमना॥",
            "निराकार है ज्योति तुम्हारी।",
            "सब जग में दीप जलाए रहतीं तुम्हारी॥",
            "रूप निराला देखन वाला।",
            "लख लख जन को तुमने पाला॥",
            "जय लक्ष्मी माँ तुमको वंदना।",
            "तुम पर निश्चय मेरा मन रमना॥",
            "गनेश विष्णु महाराज शंभु।",
            "तिनसे ही दया हो रही तुम्हीं से सब कुछ दौलत है तुम्हीं करने वाली॥",
            "धूप दीप फल मेवा मिठाई।",
            "माँ तुम्हारे चरणों में सजाई॥",
            "पुष्प गंध धूप दीप चढ़ाए।",
            "श्रद्धा भक्ति माँ से रखना तुम चाहिए॥",
            "जय लक्ष्मी माँ तुमको वंदना।",
            "तुम पर निश्चय मेरा मन रमना॥",
            "आरती जगदम्बे की, श्री लक्ष्मी की आरती।",
            "जो माँ को सदा पढ़े, उसकी सुख-समृद्धि सारी बरसे॥",
            "जय लक्ष्मी माँ तुमको वंदना।",
            "तुम पर निश्चय मेरा मन रमना॥",
        ],
        "aarti_transliteration": [
            "Jaya Lakṣhmī mā tumko vandanā.",
            "Tuma para niścaya merā mana ramanā.",
            "Nirākāra hai jyotī tumhārī.",
            "Saba jaga meṃ dīpa jalāye rahtīṃ tumhārī.",
            "Rūpa nirāla dekhana vālā.",
            "Lakh lakh jana ko tumne pālā.",
            "Jaya Lakṣhmī mā tumko vandanā.",
            "Tuma para niścaya merā mana ramanā.",
            "Ganeśa Viṣṇu Mahārāja Śambhu.",
            "Tinaseī dayā ho rahī tumhīṃ se saba kucha daulata hai tumhīṃ karane vālī.",
            "Dhūpa dīpa phala mevā miṭhāī.",
            "Mā tumhāre charaṇo meṃ sajāī.",
            "Puṣpha gaṃdha dhūpa dīpa chaṛhāye.",
            "Śraddhā bhakti mā se rakhnā tum chāhīye.",
            "Jaya Lakṣhmī mā tumko vandanā.",
            "Tuma para niścaya merā mana ramanā.",
            "Āratī jagadambake Śrī Lakṣhmī kī āratī.",
            "Jo mā sadā paṛhe, uskī sukha-samṛddhi sārī barse.",
            "Jaya Lakṣhmī mā tumko vandanā.",
            "Tuma para niścaya merā mana ramanā.",
        ],
    },
    {
        "id": "durga_aarti",
        "deity": "Goddess Durga",
        "aarti_name": "आरती जगदम्बे की, श्री दुर्गा की आरती",
        "language": "Hindi",
        "description": "Popular aarti for Goddess Durga, performed during Navratri and other festivals.",
        "aarti_hindi": [
            "आरती जगदम्बे की, श्री दुर्गा की आरती।",
            "जो माँ को सदा पढ़े, उसकी सुख-समृद्धि सारी बरसे॥",
            "जगत विख्यात तुम्हारी, माँ जगदम्बे।",
            "तुम से ही सृष्टि का पालन, तुम्हीं जगत को देती रहतीं संतान की सुख शांति॥",
            "दुर्गा माँ नाम तुम्हारा, सब का भला करने वाली।",
            "शत्रु का नाश करने वाली, मंगल कर्ता माता तुम सबकी रक्षा करने वाली॥",
            "आरती जगदम्बे की, श्री दुर्गा की आरती।",
            "जो माँ को सदा पढ़े, उसकी सुख-समृद्धि सारी बरसे॥",
            "शेर पर सवार हो करके, दानव दल का नाश करतीं।",
            "भक्तों के संकट मिटातीं, सदा सुख-समृद्धि देतीं माँ तुम सबकी भली करने वाली हो॥",
            "नवरात्रि के नौ दिन, माँ की पूजा होती है।",
            "श्रद्धा भक्ति से जो पढ़े, उसकी सभी मनोकामनाएं पूरी होती हैं॥",
            "आरती जगदम्बे की, श्री दुर्गा की आरती।",
            "जो माँ को सदा पढ़े, उसकी सुख-समृद्धि सारी बरसे॥",
            "माँ दुर्गा की आरती जो गावे।",
            "सुख-समृद्धि उसके घर आवे, कष्ट मिट जाएँ सारे॥",
            "आरती जगदम्बे की, श्री दुर्गा की आरती।",
            "जो माँ को सदा पढ़े, उसकी सुख-समृद्धि सारी बरसे॥",
        ],
        "aarti_transliteration": [
            "Āratī jagadambake Śrī Durgā kī āratī.",
            "Jo mā sadā paṛhe, uskī sukha-samṛddhi sārī barse.",
            "Jagata vikhyāta tumhārī, mā jagadambē.",
            "Tum se hī sṛṣṭi kā pālana, tumhīṃ jagata ko detī rahtīṃ santān kī sukha śānti.",
            "Durgā mā nāma tumhārā, sab kā bhalā karane vālī.",
            "Śatru kā nāśa karane vālī, maṅgala kartā mātā tum sabakī rakṣhā karane vālī.",
            "Āratī jagadambake Śrī Durgā kī āratī.",
            "Jo mā sadā paṛhe, uskī sukha-samṛddhi sārī barse.",
            "Śēra para sāvāra ho karake, dānava dala kā nāśa kartīṃ.",
            "Bhakto ke saṅkaṭ mitātīṃ, sadā sukha-samṛddhi detīṃ mā tum sabakī bhalī karane vālī ho.",
            "Navarātri ke nava dina, mā kī pūjā hotī hai.",
            "Śraddhā bhakti se jo paṛhe, uskī sabhī manokāmānāeṃ pūrī hotī haiṃ.",
            "Āratī jagadambake Śrī Durgā kī āratī.",
            "Jo mā sadā paṛhe, uskī sukha-samṛddhi sārī barse.",
            "Mā Durgā kī āratī jo gāve.",
            "Sukha-samṛddhi uske ghar āve, kaṇṭha miṭa jāeṃ sāre.",
            "Āratī jagadambake Śrī Durgā kī āratī.",
            "Jo mā sadā paṛhe, uskī sukha-samṛddhi sārī barse.",
        ],
    },
    {
        "id": "shiv_aarti",
        "deity": "Lord Shiva",
        "aarti_name": "जय शिव ओंकारा, बम भोलेनाथ",
        "language": "Hindi",
        "description": "Popular aarti for Lord Shiva, performed during Mahashivratri and Mondays.",
        "aarti_hindi": [
            "जय शिव ओंकारा, बम भोलेनाथ।",
            "त्रिशूल धारी, महेश्वर विभु॥",
            "कर में श्रेष्ठ चल त्रिशूल, नयन में नील रंग।",
            "बन बन में विराजे, सदा शिव ही सबके संग॥",
            "गल में भूषण नाग, कान में कुंडल शोभित।",
            "गंगा बहे जटा में, सदा शिव सुखदाई हैं॥",
            "जय शिव ओंकारा, बम भोलेनाथ।",
            "त्रिशूल धारी, महेश्वर विभु॥",
            "वाहन हैं नंदी गौरी, पार्वती संग विराजत।",
            "गणपति और कार्तिकेय, सब देवता साथ सज रहते॥",
            "शिवलिंग पर जल चढ़ाएं, बेलपत्र श्रद्धा से।",
            "शिव भक्ति जिसके हृदय में, उसे मोक्ष की प्राप्ति है॥",
            "जय शिव ओंकारा, बम भोलेनाथ।",
            "त्रिशूल धारी, महेश्वर विभु॥",
            "शिव की आरती जो गावे।",
            "सुख-समृद्धि उसके घर आवे, कष्ट मिट जाएँ सारे॥",
            "जय शिव ओंकारा, बम भोलेनाथ।",
            "त्रिशूल धारी, महेश्वर विभु॥",
        ],
        "aarti_transliteration": [
            "Jaya Śiva Oṃkāra, Bham Bholenātha.",
            "Triśūla Dhārī, Maheśvara Vibhu.",
            "Kara meṃ śreṣṭha cala triśūla, nayana meṃ nīla ranga.",
            "Bana bana meṃ virāje, sadā Śiva hī sabake saṅga.",
            "Gala meṃ bhūṣaṇa nāga, kāna meṃ kuṇḍala śobhita.",
            "Gaṅgā bahe jaṭā meṃ, sadā Śiva sukhadāī haiṃ.",
            "Jaya Śiva Oṃkāra, Bham Bholenātha.",
            "Triśūla Dhārī, Maheśvara Vibhu.",
            "Vāhana haiṃ Nandī Gaurī, Pārvatī saṅga virājata.",
            "Gaṇapati aura Kārttikeya, saba devatā sātha saja rahte.",
            "Śivlinga para jala chaṛhāyeṃ, belapatra śraddhā se.",
            "Śiva bhakti jisake hṛdaya meṃ, use mokṣha kī prāpti hai.",
            "Jaya Śiva Oṃkāra, Bham Bholenātha.",
            "Triśūla Dhārī, Maheśvara Vibhu.",
            "Śiva kī āratī jo gāve.",
            "Sukha-samṛddhi usake ghar āve, kaṇṭha miṭa jāeṃ sāre.",
            "Jaya Śiva Oṃkāra, Bham Bholenātha.",
            "Triśūla Dhārī, Maheśvara Vibhu.",
        ],
    },
    {
        "id": "hanuman_aarti",
        "deity": "Lord Hanuman",
        "aarti_name": "आरती की जय श्री गणेश देवा",
        "language": "Hindi",
        "description": "Popular aarti for Lord Hanuman, performed on Tuesdays and Saturdays.",
        "aarti_hindi": [
            "आरती की जय श्री गणेश देवा।",
            "जय हनुमान प्रभु, शक्ति धामा॥",
            "वीर हनुमत बल पर धीर।",
            "महाबीर बजरंगी, जय जय जय श्री राम धुरंधर की।",
            "पवन तनय बल पवन तनय बल पवन तनय बल।",
            "संकट मोचन हनुमत विख्यात।",
            "जग निवास अतुलित बल जाता॥",
            "बुद्धिर्बल यशो धैर्य, निर्भयता अमित विक्रम।",
            "जाप्य पवित्र चंचल कपि, जो सुनके कुसल विक्रम॥",
            "जो सत बार पाठ कर कोई।",
            "छूटहि बंदि महा सुख होई॥",
            "जो यह पढ़ै हनुमान चालीसा।",
            "हय सिद्दि साखी गौरीसा॥",
            "तुलसीदास सदा हरि चेरा।",
            "कीजै नाथ हृदय मँह डेरा॥",
            "पवनतनय संकट हरन, मंगल मूरति रूप।",
            "रामलखन सीता सहित, हृदय बसहु सुर भूप॥",
        ],
        "aarti_transliteration": [
            "Āratī kī jaya Śrī Gaṇeśa devā.",
            "Jaya Hanumāna prabhu, śakti dhāmā.",
            "Vīra Hanumata bala para dhīra.",
            "Mahābīra Bajrangī, jaya jaya jaya Śrī Rāma dhuradhara kī.",
            "Pavana tanaya bala pavana tanaya bala pavana tanaya bala.",
            "Saṅkata mochana Hanumata vikhyāta.",
            "Jaga nivāsa atulita bala jātā.",
            "Buddhirbala yasho dhairya, nirbhayatā amita vikrama.",
            "Jāpya pavitra chanchala kapi, jo sunake kusala vikrama.",
            "Jo sata bāra pāṭha kara koī.",
            "Chhuṭahi bandi mahā sukh hoī.",
            "Jo yaha paṛhai Hanumāna chālīsā.",
            "Haya siddhi sākhī Gaurīsā.",
            "Tulasīdāsa sadā Harī cherā.",
            "Kījai nātha hṛdaya mah̐ ḍerā.",
            "Pavanatanaya saṅkata harana, mangala mūrati rūpa.",
            "Rāmalakhana Sītā sahita, hṛdaya basahu sura bhūpa.",
        ],
    },
    {
        "id": "sandhya_aarti",
        "deity": "All Deities",
        "aarti_name": "आरती श्री गणेश जी की",
        "language": "Hindi",
        "description": "Evening sandhya aarti performed at dusk in temples and homes across India.",
        "aarti_hindi": [
            "आरती श्री गणेश जी की।",
            "उत्तम गति दीन की दाता।",
            "सुख समृद्धि प्रदान कर्ता॥",
            "जय गणेश देवा।",
            "माता जाकी पार्वती पिता महादेवा॥",
            "एक दंत दयावंत, चार भुजा धरी।",
            "माथे पर तिलक सोहे, मूसे की सवारी॥",
            "पान चढ़े फल चढ़े और चढ़े मेवा।",
            "लड्डुओं का भोग लगे, संत करें सेवा॥",
            "जय गणेश देवा।",
            "माता जाकी पार्वती पिता महादेवा॥",
            "दिन श्रद्धा की तिथि और मधुर नाम।",
            "शंकर सुमिरे संकट हरे मंगल काम॥",
            "जय गणेश देवा।",
            "माता जाकी पार्वती पिता महादेवा॥",
            "देवता यह बड़े दयाल, श्रद्धा रखो फल पाओ।",
            "मंदिर में बैठे गणपति, जन बलिहारे जाओ॥",
            "जय गणेश देवा।",
            "माता जाकी पार्वती पिता महादेवा॥",
            "गणपति बप्पा मोरया, मंगल मूर्ति रूप।",
            "श्री गणेश उद्धार करे, संकट मोचन स्वरूप॥",
            "जय गणेश देवा।",
            "माता जाकी पार्वती पिता महादेवा॥",
        ],
        "aarti_transliteration": [
            "Āratī Śrī Gaṇeśa jī kī.",
            "Uttama gati dīna kī dātā.",
            "Sukha samṛddhi pradāna kartā.",
            "Jaya Gaṇeśa devā.",
            "Mātā jākī Pārvatī pitā Mahādevā.",
            "Eka danta dayāvaṃta, chāru bhujā dharī.",
            "Māthe para tilaka sohe, mūse kī savārī.",
            "Pāna chaṛhe phala chaṛhe aura chaṛhe mevā.",
            "Laḍḍuōṅ kā bhoga lage, santa kare sevā.",
            "Jaya Gaṇeśa devā.",
            "Mātā jākī Pārvatī pitā Mahādevā.",
            "Dina śraddhā kī tithi aura madhura nāma.",
            "Śaṅkara sumire saṅkaṭ hare maṅgala kāma.",
            "Jaya Gaṇeśa devā.",
            "Mātā jākī Pārvatī pitā Mahādevā.",
            "Devatā yaha baḍe dayāla, śraddhā rakho phala pāo.",
            "Maṃdira meṃ baiṭhe Gaṇapati, jana balihāre jāo.",
            "Jaya Gaṇeśa devā.",
            "Mātā jākī Pārvatī pitā Mahādevā.",
            "Gaṇapati Bappā Moraya, maṅgala mūrti rūpa.",
            "Śrī Gaṇeśa uddhāra kare, saṅkaṭ mocana svārūpa.",
            "Jaya Gaṇeśa devā.",
            "Mātā jākī Pārvatī pitā Mahādevā.",
        ],
    },
    {
        "id": "aarti_kunj_bihari",
        "deity": "Lord Krishna",
        "aarti_name": "आरती कुँजबिहारी की श्री वृजनाथ की",
        "language": "Hindi",
        "description": "Beloved aarti of Lord Krishna, performed during Janmashtami and evening worship.",
        "aarti_hindi": [
            "आरती कुँजबिहारी की श्री वृजनाथ की।",
            "ध्यान वर्धन मंगल मूरति दुख विनाशिनी की॥",
            "गोवर्धन पर धारणी।",
            "जमुना तट विहारिनी॥",
            "आरती कुँजबिहारी की।",
            "श्री वृजनाथ की॥",
            "मोर मुकुट मुरली धर करे।",
            "मन मोहन अंग में भर करे॥",
            "सुंदर बन श्री वृजराज जाएं।",
            "गोपियाँ संग में गाएं॥",
            "आरती कुँजबिहारी की।",
            "श्री वृजनाथ की॥",
            "नंद के लाल की जय।",
            "जशोदा के लाल की जय।",
            "गोपियों वाले कन्हैया की जय।",
            "ब्रज में रहने वाले कन्हैया की जय॥",
            "आरती कुँजबिहारी की।",
            "श्री वृजनाथ की॥",
            "राधा रमण हरि वासुदेव।",
            "श्री गोविंद जय जय देव॥",
            "आरती कुँजबिहारी की।",
            "श्री वृजनाथ की॥",
        ],
        "aarti_transliteration": [
            "Āratī kũjabihārī kī Śrī vṛjanātha kī.",
            "Dhyāna vardhana maṅgala mūrati duka vināśinī kī.",
            "Govardhana par dhāraṇī.",
            "Jamunā taṭa vihārinī.",
            "Āratī kũjabihārī kī.",
            "Śrī vṛjanātha kī.",
            "Mora mukuṭa muralee dhara kare.",
            "Mana mohana aṅga meṃ bhara kare.",
            "Sundara bana Śrī vṛjarāja jāeṃ.",
            "Gopiyāṃ saṅga meṃ gāeṃ.",
            "Āratī kũjabihārī kī.",
            "Śrī vṛjanātha kī.",
            "Nanda ke lāla kī jaya.",
            "Jaśodā ke lāla kī jaya.",
            "Gopiyõ vāle Kanhaiyā kī jaya.",
            "Vraja meṃ rahanе vāle Kanhaiyā kī jaya.",
            "Āratī kũjabihārī kī.",
            "Śrī vṛjanātha kī.",
            "Rādhā Ramaṇa Hari Vāsudeva.",
            "Śrī Govinda jaya jaya deva.",
            "Āratī kũjabihārī kī.",
            "Śrī vṛjanātha kī.",
        ],
    },
]


# ---------------------------------------------------------------------------
# Categories — Mantra classification by deity, purpose, and planet
# ---------------------------------------------------------------------------

MANTRA_CATEGORIES = {
    "deity": [
        {"id": "ganesha", "name": "Lord Ganesha", "description": "Remover of obstacles, lord of beginnings", "mantra_count": 1},
        {"id": "shiva", "name": "Lord Shiva", "description": "The destroyer of evil and transformer", "mantra_count": 2},
        {"id": "vishnu", "name": "Lord Vishnu", "description": "The preserver and sustainer of the universe", "mantra_count": 1},
        {"id": "rama", "name": "Lord Rama", "description": "The ideal man, embodiment of dharma", "mantra_count": 1},
        {"id": "krishna", "name": "Lord Krishna", "description": "The divine lover and teacher of Bhagavad Gita", "mantra_count": 1},
        {"id": "hanuman", "name": "Lord Hanuman", "description": "The monkey god of courage and devotion", "mantra_count": 1},
        {"id": "lakshmi", "name": "Goddess Lakshmi", "description": "The divine mother of wealth and prosperity", "mantra_count": 1},
        {"id": "saraswati", "name": "Goddess Saraswati", "description": "The divine mother of knowledge and arts", "mantra_count": 1},
        {"id": "durga", "name": "Goddess Durga", "description": "The invincible protector and destroyer of evil", "mantra_count": 1},
        {"id": "surya", "name": "Sun God (Surya)", "description": "The source of all life and energy", "mantra_count": 1},
        {"id": "chandra", "name": "Moon God (Chandra)", "description": "The lord of mind and emotions", "mantra_count": 1},
        {"id": "savitr", "name": "Savitr (Sun God)", "description": "The divine light that illuminates the mind", "mantra_count": 1},
    ],
    "purpose": [
        {"id": "health", "name": "Health & Healing", "description": "Mantras for physical and mental well-being", "mantra_count": 2, "related_mantras": ["mahamrityunjaya_mantra", "surya_mantra"]},
        {"id": "wealth", "name": "Wealth & Prosperity", "description": "Mantras to attract abundance and financial stability", "mantra_count": 2, "related_mantras": ["lakshmi_mantra", "guru_mantra"]},
        {"id": "love", "name": "Love & Relationships", "description": "Mantras to strengthen bonds and attract love", "mantra_count": 2, "related_mantras": ["krishna_mantra", "shukra_mantra"]},
        {"id": "career", "name": "Career & Success", "description": "Mantras for professional growth and new ventures", "mantra_count": 1, "related_mantras": ["ganesh_mantra"]},
        {"id": "peace", "name": "Peace & Tranquility", "description": "Mantras for inner peace and spiritual calm", "mantra_count": 4, "related_mantras": ["vishnu_mantra", "shiva_mantra", "raam_mantra", "chandra_mantra", "ketu_mantra"]},
        {"id": "wisdom", "name": "Wisdom & Knowledge", "description": "Mantras to enhance intelligence and learning", "mantra_count": 3, "related_mantras": ["gayatri_mantra", "saraswati_mantra", "budh_mantra"]},
        {"id": "protection", "name": "Protection & Safety", "description": "Mantras to ward off evil and negative energies", "mantra_count": 5, "related_mantras": ["durga_mantra", "hanuman_mantra", "mangal_mantra", "shani_mantra", "rahu_mantra"]},
        {"id": "success", "name": "Success & Auspiciousness", "description": "Mantras for removing obstacles and ensuring success", "mantra_count": 1, "related_mantras": ["ganesh_mantra"]},
    ],
    "planet": [
        {"id": "sun", "name": "Sun (Surya)", "description": "Authority, leadership, confidence, and vitality", "mantra_count": 2, "related_mantras": ["gayatri_mantra", "surya_mantra", "raam_mantra"]},
        {"id": "moon", "name": "Moon (Chandra)", "description": "Mind, emotions, intuition, and feminine energy", "mantra_count": 1, "related_mantras": ["chandra_mantra"]},
        {"id": "mars", "name": "Mars (Mangal)", "description": "Courage, strength, energy, and warrior spirit", "mantra_count": 2, "related_mantras": ["durga_mantra", "mangal_mantra"]},
        {"id": "mercury", "name": "Mercury (Budh)", "description": "Intelligence, communication, commerce, and wit", "mantra_count": 1, "related_mantras": ["budh_mantra"]},
        {"id": "jupiter", "name": "Jupiter (Brihaspati/Guru)", "description": "Wisdom, fortune, expansion, and spiritual growth", "mantra_count": 3, "related_mantras": ["vishnu_mantra", "saraswati_mantra", "krishna_mantra", "guru_mantra"]},
        {"id": "venus", "name": "Venus (Shukra)", "description": "Love, beauty, luxury, and artistic expression", "mantra_count": 2, "related_mantras": ["lakshmi_mantra", "shukra_mantra"]},
        {"id": "saturn", "name": "Saturn (Shani)", "description": "Discipline, patience, karma, and longevity", "mantra_count": 4, "related_mantras": ["mahamrityunjaya_mantra", "hanuman_mantra", "shiva_mantra", "shani_mantra"]},
        {"id": "rahu", "name": "Rahu (North Lunar Node)", "description": "Illusions, desires, karmic lessons, and sudden changes", "mantra_count": 1, "related_mantras": ["rahu_mantra"]},
        {"id": "ketu", "name": "Ketu (South Lunar Node)", "description": "Spirituality, liberation, past-life karma", "mantra_count": 1, "related_mantras": ["ketu_mantra", "ganesh_mantra"]},
    ],
}


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/daily")
async def get_daily_mantra():
    """Returns a random daily mantra with meaning, benefits, and deity."""
    mantra = random.choice(DAILY_MANTRAS)
    return {
        "date": date.today().isoformat(),
        "mantra": mantra,
    }


@router.get("/chalisa")
async def get_chalisas():
    """Returns a list of Hindu chalisas with full text."""
    return {
        "total": len(CHALISAS),
        "chalisas": CHALISAS,
    }


@router.get("/aarti")
async def get_aartis():
    """Returns a list of popular aartis with full text."""
    return {
        "total": len(AARTIS),
        "aartis": AARTIS,
    }


@router.get("/categories")
async def get_mantra_categories():
    """Returns mantra categories: deity, purpose, and planet-based.

    Counts and member ids are derived from `DAILY_MANTRAS`; see `_members`.
    """
    return _categories()


@router.get("")
async def list_mantras(
    purpose: str | None = Query(None, description="Purpose category id"),
    planet: str | None = Query(None, description="Planet category id"),
    deity: str | None = Query(None, description="Deity category id"),
    q: str | None = Query(None, min_length=1, description="Free-text search"),
):
    """List mantras, optionally narrowed by category or free text.

    `/categories` reported a count and a list of ids, and until now no endpoint
    served those mantras -- a category could be counted but never opened.
    """
    results = list(DAILY_MANTRAS)
    if purpose:
        results = [m for m in results if m.get("purpose") == purpose]
    if planet:
        results = [m for m in results if (m.get("planet") or "").lower() == planet.lower()]
    if deity:
        results = [m for m in results if deity.lower() in (m.get("deity") or "").lower()]
    if q:
        needle = q.lower()
        results = [
            m for m in results
            if any(
                needle in (m.get(field) or "").lower()
                for field in ("id", "deity", "transliteration", "mantra_hindi",
                              "meaning", "benefits", "purpose", "planet")
            )
        ]
    return {"total": len(results), "mantras": results}


@router.get("/{mantra_id}")
async def get_mantra(mantra_id: str):
    """One mantra by id. Declared last so `/daily` and friends still match."""
    for mantra in DAILY_MANTRAS:
        if mantra["id"] == mantra_id:
            return {"mantra": mantra}
    raise HTTPException(status_code=404, detail="Mantra not found.")
